### ISSUE TITLE
I solved the challenge how i can submit the flag

### ISSUE THREAD

**Issue by Juliaria08** [LiveOverflow/ctf#7]
How to submit the flag

**Comment by LiveOverflow** [comment]
there is no submission

**Comment by Juliaria08** [comment]
and how i can check that the flag its correct?

**Comment by LiveOverflow** [comment]
if you have it, you know it's correct.

You can of course also write me a twitter DM, reddit DM or old-school email, send me the flag and a few words on how you found it and I can tell you if it is correct. There is no need for a submission.

**Comment by Juliaria08** [comment]
ok
